#ifndef _KERNEL_SYSCALL_H_
#define _KERNEL_SYSCALL_H_

#include <sys/types.h>
#include <kernel/pm/process.h>

typedef int (*SYSCALL)( struct PROCESS_STACK * );

enum
{
	SYSCALL_MININDEX=0,
	
	SYSCALL_OPEN=0,
	
SYSCALL_TEST,
	
	SYSCALL_CLOSE,
	SYSCALL_READ,
	SYSCALL_WRITE,
	SYSCALL_SEEK,
	SYSCALL_CONTROL,
	SYSCALL_MOUNT,
	SYSCALL_UNMOUNT,
	SYSCALL_CREATE,
	SYSCALL_DELETE,
	SYSCALL_RENAME,
	SYSCALL_COPY,
	SYSCALL_LIST,
	SYSCALL_SPAWN,
	SYSCALL_KILL,
	SYSCALL_SLEEP,
	SYSCALL_WAKE,
	SYSCALL_WAIT,
	SYSCALL_LOAD,
	SYSCALL_MORECORE,
	
	SYSCALL_MAXINDEX=SYSCALL_MORECORE,
	SYSCALL_MAXCALLS
};

int syscall_init( void );

#endif
